### ISSUE TITLE
doesn't build on macOS 10.14.x

### ISSUE THREAD

**Issue by tessus** [AviSynth/AviSynthPlus#156]
I get a bunch of errors when I try to compile this on macOS 10.14.6:

```
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:100:27: error: 'path' is unavailable: introduced in macOS 10.15
  return fs::absolute(fs::path(f).lexically_normal()).generic_string();
                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:739:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:100:23: error: 'path' is unavailable: introduced in macOS 10.15
  return fs::absolute(fs::path(f).lexically_normal()).generic_string();
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:773:3: note: 'path' has been explicitly marked unavailable here
  path(const _Source& __src, format = format::auto_format) {
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:100:23: error: '~path' is unavailable: introduced in macOS 10.15
  return fs::absolute(fs::path(f).lexically_normal()).generic_string();
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:791:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:100:35: error: 'lexically_normal' is unavailable: introduced in macOS 10.15
  return fs::absolute(fs::path(f).lexically_normal()).generic_string();
                                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:1110:8: note: 'lexically_normal' has been explicitly marked unavailable here
  path lexically_normal() const;
       ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:100:35: error: '~path' is unavailable: introduced in macOS 10.15
  return fs::absolute(fs::path(f).lexically_normal()).generic_string();
                                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:791:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:100:14: error: 'absolute' is unavailable: introduced in macOS 10.15
  return fs::absolute(fs::path(f).lexically_normal()).generic_string();
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:1477:39: note: 'absolute' has been explicitly marked unavailable here
inline _LIBCPP_INLINE_VISIBILITY path absolute(const path& __p) {
                                      ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:100:10: error: '~path' is unavailable: introduced in macOS 10.15
  return fs::absolute(fs::path(f).lexically_normal()).generic_string();
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:791:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:100:55: error: 'generic_string' is unavailable: introduced in macOS 10.15
  return fs::absolute(fs::path(f).lexically_normal()).generic_string();
                                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:1019:15: note: 'generic_string' has been explicitly marked unavailable here
  std::string generic_string() const { return __pn_; }
              ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:27: error: 'directory_iterator' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:2408:7: note: 'directory_iterator' has been explicitly marked unavailable
      here
class directory_iterator {
      ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:110: error: 'operator|' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                                                                                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:455:36: note: 'operator|' has been explicitly marked unavailable here
inline constexpr directory_options operator|(directory_options _LHS,
                                   ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:46: error: 'path' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:773:3: note: 'path' has been explicitly marked unavailable here
  path(const _Source& __src, format = format::auto_format) {
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:46: error: '~path' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:791:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:23: error: 'directory_iterator' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:2429:3: note: 'directory_iterator' has been explicitly marked unavailable
      here
  directory_iterator(const path& __p, directory_options __opts,
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:23: error: 'directory_iterator' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:2429:3: note: 'directory_iterator' has been explicitly marked unavailable
      here
  directory_iterator(const path& __p, directory_options __opts,
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:23: error: '~directory_iterator' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:2445:3: note: '~directory_iterator' has been explicitly marked unavailable
      here
  ~directory_iterator() = default;
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:21: error: 'begin' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:2498:1: note: 'begin' has been explicitly marked unavailable here
begin(directory_iterator __iter) noexcept {
^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:21: error: 'directory_iterator' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:2433:3: note: 'directory_iterator' has been explicitly marked unavailable
      here
  directory_iterator(const directory_iterator&) = default;
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:21: error: '~directory_iterator' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:2445:3: note: '~directory_iterator' has been explicitly marked unavailable
      here
  ~directory_iterator() = default;
  ^
/Users/Shared/ffmpeg/compile/AviSynthPlus-3.5.1/avs_core/core/PluginManager.cpp:619:21: error: '~directory_iterator' is unavailable: introduced in macOS 10.15
    for (auto& file : fs::directory_iterator(dir, std::filesystem::directory_options::skip_permission_denied | std::filesystem::directory_options::follow_directory_symlink, ec))
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:2445:3: note: '~directory_iterator' has been explicitly marked unavailable
      here
  ~directory_iterator() = default;
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [avs_core/CMakeFiles/AvsCore.dir/core/PluginManager.cpp.o] Error 1
make[1]: *** [avs_core/CMakeFiles/AvsCore.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by qyot27** [comment]
Unfortunately, Apple only supports C++17's `<filesystem>` capabilities with their toolchain on Catalina.  On High Sierra and Mojave, you have to use GCC 8 or 9 (additionally, using Ninja instead of Make means not having to explicitly add linker flags for libstdc++).  Upstream LLVM/Clang may or may not also be affected by the same issue on macOS, even though on Linux and FreeBSD it works.

[The relevant section in the docs.](https://github.com/AviSynth/AviSynthPlus/blob/master/distrib/docs/english/source/avisynthdoc/contributing/posix.rst#macos)

**Comment by tessus** [comment]
Wow, ok, so this means no avisynth for me then. Too bad, but I won't install gcc8/gcc9 when I have clang installed which is clang-1100.0.33.17. I guess writing portable code is not done anymore these days. Well, I'm too old for installing 5 different compilers and chasing after the latest compiler features.

**Comment by pinterf** [comment]
At the moment the core is under heavy development, we'll probably do a workaround later when the those things are finished.

**Comment by qyot27** [comment]
It turns out that it was easier to hack in than I thought.  It probably needs to be tweaked a bit more (the bit in the commit message about the CMAKE_CXX_FLAGS, for example), but I tested it on Mojave and it worked.
```
git clone git://github.com/AviSynth/AviSynthPlus.git
cd AviSynthPlus
curl -o macavsfs.patch "https://github.com/qyot27/AviSynthPlus/commit/293b4dac467d7b2cd7771cd47d949075e88a1949.patch"
git am macavsfs.patch

git submodule init
git submodule update

mkdir avisynth-build && cd avisynth-build
cmake ../ -DENABLE_FILESYSTEM_COMPAT:bool=on
make -j$(nproc)
sudo make install
```

**Comment by qyot27** [comment]
Like pinterf said, though, it getting into the master branch may need to wait.
