### ISSUE TITLE
"Too many arguments to function" after upgrade to 3.6.0

### ISSUE THREAD

**Issue by aportale** [AviSynth/AviSynthPlus#166]
My plugin adds a function to the environment (IScriptEnvironment) like this:
> env->AddFunction("QtAviSynthElements", "[clip]c[elements]s*", StillImage::CreateElements, nullptr);
[source](https://github.com/aportale/qtorials/blob/master/tools/qtavisynth/qtavisynth.cpp#L32)

The function parameter _elements_ is meant to be a string array of variable length, which is later read via _AVSValue::ArraySize()_ and _AVSValue::[]_ [source](https://github.com/aportale/qtorials/blob/master/tools/qtavisynth/stillimage.cpp#L19).

The function is called like this in the .avs script:
> QtAviSynthElements("rgbpatterns", "qtlogosmall") [source](https://github.com/aportale/qtorials/blob/master/screencasts/test/qtavisynth_rgbpattern.avs#L3)

That used to work fine since a couple of AviSynth and AviSynth+ versions. After upgrading to AviSynth+ 3.6.0, I am now getting a error message.
> Avisynth open failure: Too many arguments to function QtAviSynthElements

Did somthing in the parameter definition format change for arrays with variable length? Or in the way how to call the function in an .avs script?

**Comment by pinterf** [comment]
Thanks, until I look into it, does it happen when first argument is not a named one or simple a []c? (named arguments are optional)

**Comment by pinterf** [comment]
Theoretically, until 3.6 you cannot have a named parameter which is and array.
I'm surprised that is was allowed so far, because you could not use the name as a reference in scripts

Since 3.6 named arrays are allowed, calling with either 
Blank.YourFunction(["string2","string2"])
or
Blank.YourFunction(elements=["string2","string2"])

Or: you remove the parameter name from the definition: [clip]cs*

Anyway, I'll check it later, why it has been changed.

(As a note, in present syntax, all your parameters are optional, even the clip because it is named.)

**Comment by aportale** [comment]
"[clip]cs*" fixes my issue! Great :) Indeed, naming a variable-sized array doesn't make much sense, now that I think of it. So, 3.6.0 is simply more strict about it.

Thank you also for the note. I will remove the name for clip parameter, since that is everything but optional.

**Comment by pinterf** [comment]
Not only more strict, but it now allows using it.
But then you have to provide a real array, put the array elements with the new array syntax, as it was shown above.

**Comment by aportale** [comment]
OK, now I also understand the new Array syntax. Which I find very useful and will use.
Thank you again!

**Comment by pinterf** [comment]
Note: it's not compatible with older Avisynth versions. For more info on arrays (mostly on script side), look in readme_history.txt under the distrib folder.

**Comment by aportale** [comment]
From my POV, this issue can be closed. It does serve as hint for plugin authors who encounter the same problem.

**Comment by pinterf** [comment]
Well if you have time, I'd like to ask you for one more test:
please try your _original_ versions with test build 6.
https://forum.doom9.org/showthread.php?t=181351
I found another plugin (MP_PipeLine) that was using named arrays internally, so it turned out that it was allowed despite that from script you were not able to fill them by name, but by using as unnamed parameter sequence - or filled from a filter programatically - they worked.

**Comment by aportale** [comment]
Thank you. I tried the test build 6 by unpacking the .7z and setting Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{E6D6B700-124D-11D4-86F3-DB80AFD98778}\InProcServer32:(Default) to the path of the unpacked AviSynth.dll

I can confirm that my old plugin/avs-script combination which caused the "Too many arguments to function" error in 3.6.0, now works well again with the 3.6.1_20200604_test6 version. Thank you!

Was the fix beadf145f65fb60d018de888533113182372f854 ?

**Comment by aportale** [comment]
> Was the fix beadf14 ?
(I don't think so)

**Comment by pinterf** [comment]
No. It's not in a publuc commit yet, only after having cleaned up these test codes.

**Comment by pinterf** [comment]
Fixed in 3.6.1 by this commit https://github.com/AviSynth/AviSynthPlus/commit/a244bd3a2f5331320ee47ab327630c84c033c7f6
